name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --tag ghcr.io/scy133/image-demo:latest
       docker run ghcr.io/scy133/image-demo:latest
       docker push ghcr.io/dscy133/image-demo:latest
      
      
